### ISSUE TITLE
Cross compiling?

### ISSUE THREAD

**Issue by rrix** [mischief/gopf#2]
Hi there,

I'm trying to cross compile from Linux to FreeBSD to run pf_exporter on my pfSense edge, and I'd rather not install git and go on my router. I tried to cross compile as follows, but it failed, as follows:

```
~$ GOPATH=~/Code/go GOOS=freebsd go build
# github.com/mischief/gopf
../src/github.com/mischief/gopf/pf.go:43: undefined: PF_BLOCK
../src/github.com/mischief/gopf/pf.go:44: undefined: PF_PASS
../src/github.com/mischief/gopf/pf.go:45: undefined: PF_MATCH
```

Do I need to compile this from a freebsd VM, or is there another way to cross-compile this from my main system?

**Comment by mischief** [comment]
hi @rrix!

thanks for your interest in the project.

the issue here is that i've never really used freebsd, and this code requires systemd-specific definitions.
if you look in the main repo, there's `pf_openbsd.go`, which contains the openbsd-specific definitions. there's no equivalent file for freebsd, because i never needed to use it on freebsd.

unfortunately, that file is full of some fiddly c glue code. it would take some work to get the equivalent on freebsd, so as is, the project is not compilable even on freebsd.

additionally, cross-compiling go code that uses C is extremely difficult and probably not worth the effort, so if the appropriate code is added to support freebsd's pf, it would likely be best to compile the code from within freebsd (in a vm, as you suggested).

**Comment by rrix** [comment]
That's fair, I'll poke with the snmp-exporter, or build an openbsd router (been meaning to anyways) :)

**Comment by zachfi** [comment]
@mischief What do I need to read in order to know how to make the fiddly c code work on FreeBSD?  I assume these are just the bindings to represent the data structures in the kernel, but I'm not sure how to bridge my gap in knowledge.

**Comment by mischief** [comment]
@xaque208 my recommendation is that you read up on how go interacts with c, through cgo, and get familiar with the FreeBSD specific data structures and system calls work to interact with pf.

it will probably look very similar to openbsd, but since i have never been a freebsd user, i've had no interest (and now no time) to support freebsd. please take a look at the `_openbsd.go` files in the project to see how i supported openbsd.

there will need to be similar `_freebsd.go` files added to support freebsd. some of the code may be identical - but some will probably differ due to the slightly different data structures freebsd may use.

as a first pass you might just copy the `*_openbsd.go` files to `*_freebsd.go` and try to compile on freebsd with go and see what fails.

hope that helps.

**Comment by zachfi** [comment]
Thank you @mischief.  I was able to get some of this code to run on FreeBSD, though I started fresh and borrowed from your work here to get what I was after.  My specific goal is go be able to get PF stats to represent over a prometheus exporter, as you have done for OpenBSD, so thank you for the example and the guidance.

In trying to get this code to compile on FreeBSD, it looks like there are some components in the pf.go as well that are OpenBSD specific.  I can work to move some of that around, but, the amount of code I had to comment out to approach the compile on FreeBSD was pretty high.  I'm happy to put up a PR and perhaps we can work through it, but given that I only care about the stats right now, I could bring in the OpenBSD structures to a `gopfstats` package easier than making this project compatible with both BSDs.  I use both platforms, and so this may happen at some point.

This was a fun weekend project, so thank you for providing the guidance here.  I'm working to get both https://github.com/xaque208/gopfstats and https://github.com/xaque208/pf_exporter functional on FreeBSD in the coming week.

**Comment by mischief** [comment]
@xaque208 can you please try this branch? https://github.com/mischief/gopf/tree/freebsd i have only compiled it, i do not have root access on the freebsd system i tested it on.

**Comment by zachfi** [comment]
That looks to functions identical to what I'd produced from your code.

```
fw, err = pf.Open()
a, err := fw.Stats()
```

**Comment by mischief** [comment]
@xaque208 i have tested this change on a FreeBSD 12 system. it seems to work fine, except for queues, when the loginterface is set.

**Comment by zachfi** [comment]
Thank you for taking a look at this @mischief.  If you're planning to merge that code, I'd delete the repos I started and instead start working to make sure that the `pf_exporter` you have will also work on FreeBSD.  Without looking at the code, I'd assume this would "just work".

**Comment by mischief** [comment]
@xaque208 i can try to get around to that in the next few days. i would like to deduplicate common code between freebsd and openbsd before merging, since i just copied and pasted the file and edited it to test.

i would also like to see about getting FreeBSD altq support, although i'm not sure how useful that is since FreeBSD pf queuing is a bit stunted compared to OpenBSD.

**Comment by zachfi** [comment]
I agree.  I certainly don't use the altq bits, and if they ever get around to updating PF in FreeBSD to match OpenBSD, then it will all go away anyway.  I keep hearing mumbling of that update pending, but nothing seems to happen, at least from a user's perspective.

Let me know if I can help, or test or whatever.  It was fun digging into the code to make the syscalls and reading the data structures in the pf(4) manpage.  Thank you for your efforts here.

**Comment by mischief** [comment]
@xaque208 please see https://github.com/mischief/pf_exporter/pull/5.

**Comment by zachfi** [comment]
Wonderful @mischief.  I'll try to test that out one of these evenings.

**Comment by zachfi** [comment]
@mischief that worked well for me.  Thanks for working on this.

How do you feel about vendoring the dependencies?  I'd could work up a freebsd port for this, but I think that would require all the build dependencies to be tracked for reliable build.

**Comment by ggulchin** [comment]
Apologies for the noob question. How do you compile? what commands to run? 
if I ran `go build pf.go` I get `# command-line-arguments
./pf.go:14:17: undefined: PF_BLOCK
./pf.go:15:17: undefined: PF_PASS`

if I run `go build pf_freebsd.go` 
I get `
./pf_freebsd.go:184:9: undefined: Action
./pf_freebsd.go:214:24: undefined: Addr
./pf_freebsd.go:253:49: undefined: Addr
./pf_freebsd.go:309:25: undefined: Pf
./pf_freebsd.go:313:14: undefined: Pf
./pf_freebsd.go:354:32: undefined: IfStats
./pf_freebsd.go:384:27: undefined: Stats
./pf_freebsd.go:435:41: undefined: Anchor
./pf_freebsd.go:440:30: undefined: Queue
./pf_freebsd.go:445:40: undefined: Queue
./pf_freebsd.go:445:40: too many errors
`

Looks like I'm missing something. Please help!

I run FreeBSD 13.1 with pf enabled
Thanks in advance!

**Comment by mischief** [comment]
@ggulchin you would need to use the `freebsd` branch of this repo. note that i have not attempted any porting work to freebsd since the last commit in that branch, so i don't know if it works, maybe things have changed on freebsd.

freebsd is not supported in the master branch, and i do not use freebsd.

if you get it to work and can prepare a PR to add support, i would review it.

**Comment by ggulchin** [comment]
Hi Nick! 

What worked for me was using mischief/pf_exporter (https://github.com/mischief/pf_exporter/tree/freebsd), than switching to freebsd branch and adjusting main.go file


———
[root@Fear]-pts/4:589# git diff main.go
diff --git a/main.go b/main.go
index e57963c..c5d5497 100644
--- a/main.go
+++ b/main.go
@@ -6,6 +6,8 @@ import (

        "github.com/prometheus/client_golang/prometheus"
        "github.com/prometheus/common/log"
+
+       "github.com/prometheus/client_golang/prometheus/promhttp"
 )

 var (
@@ -128,7 +130,7 @@ func main() {
        prometheus.MustRegister(exporter)

        log.Infof("Starting Server: %s", *listenAddress)
-       http.Handle(*metricsPath, prometheus.Handler())
+       http.Handle(*metricsPath, promhttp.Handler())
        http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
                w.Write([]byte(`<html>
              <head><title>pf Exporter</title></head>

———

And thing worked like magic 😀

Thanks for your help!

—gena

**Comment by mischief** [comment]
sorry for the delay in responding to this - i merged some freebsd support to the default branch. support in pf_exporter should follow soon.
